### PR TITLE
Demo code workflows

### PR DESCRIPTION
**Pull request by Sumanshekhar17**
Just testing, if you can review the changes the pull request!

### CODE REVIEW

**Review by hkershaw-brown — APPROVED** [review]
Looks good to me!

**Comment by hkershaw-brown** [comment]
@Sumanshekhar17 currently the main branch is not protected.  Would you like to have the main branch protected, e.g. one person has to review changes?

**Comment by Sumanshekhar17** [comment]
@hkershaw-brown yeah that would be great! Is that something I can do from setting?

**Comment by hkershaw-brown** [comment]
@Sumanshekhar17 yup if you go to settings, branch protection rules you should see something like this. 
You can set up a rule for main, e.g Require a pull request before merging, with X number of reviews

Screenshot 2024-06-18 at 4 22 27 PM

**Review by amrhein — APPROVED** [review]
Looks good!!

**Pull request merged**
